chas-academy/mercury-client

src/components/App.js, src/components/Views/AddItem.js, src/components/Views/Settings.js, src/index.js
=> add routing and placeholder views

src/assets/styles/style.css, src/components/GlobalNav/GlobalNav.js, src/components/index.js, src/views/Home.js
Simple navbar component with buttons has been created
=> 6 navbar component

src/DummyData.js, src/components/index.js
I have created some dummy data items.
=> closes #30 

Dockerfile.prod, exoframe.json, package.json
Closes #22 
Add react production build and new dockerfile for production use.
React builds to static html/css/js and Dockerfile uses an nginx image to serve static files.
=> #22 add production deploy config

package.json, public/index.html, src/assets/styles/style.css, src/components/App/App.js, src/components/App/App.scss, src/components/GlobalNav/GlobalNav.js, src/components/GlobalNav/GlobalNav.scss, yarn.lock
=> Closes #45

src/DummyData.js, src/components/Item/Item.js, src/components/ProgressBar/ProgressBar.js, src/components/ProgressBar/ProgressBar.scss, src/views/AddItem.js, src/views/Home.js, src/views/Settings.js
Now displays an interger percent of the progress
=> Closes #44

src/components/App/App.js, src/views/PageNotFound.js, src/views/index.js
Skapat en simpel PagenotFound view.
=> closes #57 PageNotFound 

.eslintrc.json, src/components/Button/Button.js, src/components/Card/Card.js, src/components/GlobalNav/GlobalNav.js, src/components/Item/Item.js, src/components/ProgressBar/ProgressBar.js, src/types.js
=> 61 item flow

docker-compose-dev.yml, docker-compose-production.yml
Missing networks from docker-compose files!
=> HOTFIX - Networks missing from compose files

src/components/App/App.js, src/components/LogInForm/LogInForm.js, src/components/LoginComponent/LoginComponent.js, src/components/index.js, src/views/LogIn.js, src/views/index.js
=> 28 login component

src/components/App/App.js, src/components/LineButton/LineButton.js, src/components/LineButton/LineButton.scss, src/components/Loader/Loader.js, src/components/Loader/Loader.scss, src/components/LogInForm/LogInForm.js, src/components/LogInForm/LogInForm.scss, src/components/index.js, src/containers/ItemsContainer.js
=> Some small css fixes and two new small components

src/components/AddItemWizard/AddItemWizard.js, src/components/AddItemWizard/AddItemWizard.scss, src/components/Input/Input.css, src/components/Input/Input.js, src/components/Input/Input.scss, src/components/LineButton/LineButton.scss
=> added units and remade part of input, made buttons a bit better looking

src/components/SettingsComponent/SettingsComponent.js, src/components/SettingsComponent/SettingsComponent.scss, src/components/index.js, src/views/Settings.js
=> Attributions fixed, logout button is a dummy

src/components/AddItemWizard/AddItemWizard.js, src/components/AddItemWizard/AddItemWizard.scss, src/components/App/App.scss, src/components/Input/Input.css, src/components/Input/Input.scss, src/components/StepBar/StepBar.scss
=> 120 autocomplete style

src/components/AddItemWizard/AddItemWizard.js
=> 135 canonical item field

src/actions/user.js, src/components/App/App.js, src/components/App/App.scss, src/components/LogInForm/LogInForm.js, src/components/LogOut/LogOut.js, src/components/SettingsComponent/SettingsComponent.js, src/components/index.js, src/views/Settings.js
closes #126 #127 
At the moment, I've contributed with a an annoying page reload/ redirect  as you sign out.
=> Relocate signout button to settings view

src/components/App/App.scss, src/components/Box/Box.scss, src/components/Button/Button.scss, src/components/Header/Header.scss, src/components/Item/Item.js, src/components/Item/Item.scss, src/components/ItemDetail/ItemDetail.js, src/components/ItemDetail/ItemDetail.scss, src/components/Items/Items.js, src/components/Items/Items.scss, src/components/LogInForm/LogInForm.js, src/components/PageTitle/PageTitle.scss, src/components/ProgressBar/ProgressBar.js, src/components/ProgressBar/ProgressBar.scss, src/components/SettingsComponent/SettingsComponent.js, src/components/StepBar/StepBar.scss, src/components/helpers.js, src/components/index.js
The media queries I've added to App.scss and applied to the `<main>` is a quickfix for layout responsiveness. 
Also, I've added a ItemDetail Component for displaying item data. I've created a tiny math helper file in `src/components/helpers.js` - since several components does the same calcualtions.
=> Add dynamic change of item data details & app responsiveness

src/components/App/App.scss, src/components/Box/Box.js, src/components/Box/Box.scss, src/components/Item/Item.scss, src/components/Items/Items.js, src/components/Items/Items.scss, src/components/LogInForm/LogInForm.js, src/components/SettingsComponent/SettingsComponent.js, src/components/SettingsComponent/SettingsComponent.scss, src/views/AddItem.js, src/views/Home.js, src/views/LogIn.js, src/views/PageNotFound.js, src/views/Settings.js
* Add section tag with class .content to the views, a quick way to generate cohesive layout
* Add more possible classes to Box comp, there is some repeated code but it works for now
=> Use styles from .items-class as universal content container

src/components/AddItemWizard/AddItemWizard.js, src/components/AddItemWizard/AddItemWizard.scss, src/components/App/App.scss, src/components/GlobalNav/GlobalNav.scss, src/components/Items/Items.js, src/components/LogInForm/LogInForm.js, src/components/PageTitle/PageTitle.js, src/components/PageTitle/PageTitle.scss, src/components/RegisterForm/RegisterForm.js, src/components/SettingsComponent/SettingsComponent.js, src/views/AddItem.js, src/views/Home.js, src/views/LogIn.js, src/views/Settings.js
closes #175 
This is the color-scheme using gradient backgrounds.
=> 175 color alt

src/components/App/App.js, src/components/GlobalNav/GlobalNav.js
Don't show to navbar when a user isn't signed in.
Closes #181
=> Dont show navbar when not logged in

src/actions/items.js, src/actions/user.js
Removes notifications from login and fetch items actions.
Closes #180
=> Add and remove notifications on client

src/components/AddItemWizard/AddItemWizard.js, src/components/Icon/Icon.scss, src/components/LogInForm/LogInForm.scss, src/views/LogIn.js
=> add icon to last step of add item process

src/reducers/itemReducer.js
Hotfix for decrement button not working as expected - reducers were missing 🙈
=> Fix decrement: reducers was missing

src/components/AddItemWizard/AddItemWizard.js, src/components/Icon/Icon.js, src/components/LogOut/LogOut.js, src/components/SettingsComponent/SettingsComponent.js, src/components/SettingsComponent/SettingsComponent.scss, src/components/StepBar/StepBar.scss
=> 198 stepbar line

src/components/SettingsComponent/SettingsComponent.js, src/components/Welcome/Welcome.js, src/components/Welcome/Welcome.scss, src/components/index.js, src/containers/ItemsContainer.js
=> add welcome message when there are no items fetched
